version: "3.9"

volumes:
  back: { }
  front: { }

services:
  nginx:
    image: nginx:alpine
    restart: on-failure
    ports:
      - "33667:80"
    volumes:
      - back:/var/www/html
      - front:/var/www/html/public/front
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf
    depends_on:
      - backend

  backend:
    restart: on-failure
    env_file:
      - .env
    build:
      context: https://${GITHUB_TOKEN}@github.com/Aqamarine228/CryptoInsuranceBack.git
      dockerfile: Dockerfile
    volumes:
      - back:/var/www/html

  frontend:
    restart: no
    command: yarn build
    build:
      context: https://${GITHUB_TOKEN}@github.com/Aqamarine228/CryptoInsuranceFrontend.git
      dockerfile: Dockerfile
    env_file:
      - .env
    stdin_open: true
    depends_on:
      - backend
    volumes:
      - front:/app/frontend/dist

networks:
  default:
    name: 'mysql-network'
    external: true